### ISSUE TITLE
 /unclaimall does not work for admin clusters even when in admin mode

### ISSUE THREAD

**Issue by sammyt291** [Pocketkid2/WizryLand-Debugging#1]

**Comment by Pocketkid2** [comment]
Tested on latest build?

**Comment by Pocketkid2** [comment]
So the reason behind this is: Admin chunks can be anywhere, and I don't think you'd want to unclaim the entire admin cluster, every chunk in the world. Maybe you want that. IDK

**Comment by sammyt291** [comment]
Ah i see, i was under the impression clusters were defined by adjoining chunks and /unclaimall just checked all adjacent chunks when run

**Comment by sammyt291** [comment]
so that would actually be fine to be left in that case

**Comment by Pocketkid2** [comment]
This works for regular clusters but the admin cluster doesn't have to be just one blob, it can be anywhere that's why I left it that way
