### ISSUE TITLE
removed/added message wrong way round for friend system

### ISSUE THREAD

**Issue by sammyt291** [Pocketkid2/WizryLand-Debugging#10]

**Comment by sammyt291** [comment]
take it that this one is fixed now?

**Comment by Pocketkid2** [comment]
Check it

**Comment by sammyt291** [comment]
is the dropbox the latest build?

**Comment by Pocketkid2** [comment]
Yeah. (I really need a better way to push updates)

**Comment by sammyt291** [comment]
Removed has a typo of "Remoed" for the person running the claimfriend command

**Comment by Pocketkid2** [comment]
Fixed.
