### ISSUE TITLE
Data doesn't always load correctly.

### ISSUE THREAD

**Issue by Pocketkid2** [Pocketkid2/WizryLand-Debugging#13]
There may be a large internal problem with how data is stored. The current way is to convert all serialized chunks to regular chunk objects when the plugin is loaded. This may be a problem, as sometimes when the server is started or restarted the data appears to load, but the chunks don't appear to be claimed. 

Possible/suggested solutions: (For the developer)
- ~~Schedule the loading of chunks to happen after every plugin and world is loaded properly~~ Done
- ~~Convert internal storage of data to serializable chunks as much as possible.~~ Done

**Comment by Pocketkid2** [comment]
Those two possible solutions have been tried. They don't appear to work. This may take some more time and thought, so It may take some time before this issue is completely fixed. It is worth noting that a restart can fix this, and it doesn't always impede plugin usage.

**Comment by sammyt291** [comment]
Any progress on this issue?

**Comment by Pocketkid2** [comment]
To be honest no. It is really bugging me. I have tried and tried everything I can think of, but I am still trying to figure it out. The worst part is that tomorrow I leave for a trip and I don't get back till Friday. Then i'll have Saturday only to continue work and then another trip the following week. 

As long as you don't restart your server often, the latest build should suit your purposes until I find some fixes. Thanks for your patience.

**Comment by Pocketkid2** [comment]
If you have a mySQL database for your server, I could considering changing the data storage to that instead of a flatfile. But that is a last-option idea.

**Comment by sammyt291** [comment]
we do have a mySQL server setup and in use so that is a viable option for us

**Comment by Pocketkid2** [comment]
Alright. When I get back I will look into that. Sorry for all the delays.

**Comment by Pocketkid2** [comment]
I am beginning to start working with MySQL. I hope to be able to start that today and complete it soon.

**Comment by Pocketkid2** [comment]
Finally progress can get back on schedule!

**Comment by sammyt291** [comment]
Glad to hear :+1:

**Comment by Pocketkid2** [comment]
Yeah. I'm sorry this is taking so long. MySQL will be much better in the long run, but as I have never worked with it in the least, I have to learn it all from the beginning. It'll take me a little while longer, but when it is done it'll be really awesome!

**Comment by Pocketkid2** [comment]
Also, with this new system, there are some things I want to rework just a little bit so that they will run smoother. I'd like to chat in the google doc whenever you can.

**Comment by sammyt291** [comment]
Hey man, sorry iv been so inactive here, add me on skype to get in touch with me better heh SammyT291

**Comment by Pocketkid2** [comment]
MySQL Data Storage has fixed this problem! Woooooooot!
