### ISSUE TITLE
 Admins cannot /unclaim or /unclaimall another user’s cluster even when in admin mode.

### ISSUE THREAD

**Issue by sammyt291** [Pocketkid2/WizryLand-Debugging#3]

**Comment by Pocketkid2** [comment]
Has this been tested on the latest build?

**Comment by sammyt291** [comment]
Tested now, 
/unclaim seems to do nothing at all, no output/effect/error
/unclaimall throws an error when in another users land as admin

**Comment by sammyt291** [comment]
http://pastebin.com/TJTj6CGR

**Comment by Pocketkid2** [comment]
Yes I saw this also in my testing server :) I'm on it

**Comment by Pocketkid2** [comment]
This is fixed now
